import type { Metadata } from 'next'

// Import Statics
import HeaderComponent from '@/components/static/header';
import FooterComponent from '@/components/static/footer';

import '@/assets/scss/global.scss';


export const metadata: Metadata = {
  title: 'Polinizando Costa Rica',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
          <HeaderComponent/>
          <main>
            {children}
          </main>
          <FooterComponent/>
        </body>
    </html>
  )
}
